/**
 * \internal
 * vd_cgla.h - Common Graphics Library Aliases
 * 
 * zlib License
 * 
 * (C) Copyright 2025-2026 Michael Dodis (michaeldodisgr@gmail.com)
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 * 
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */
#ifndef VD_CGLA_H
#define VD_CGLA_H
#define VD_CGLA_VERSION_MAJOR 0
#define VD_CGLA_VERSION_MINOR 0
#define VD_CGLA_VERSION_PATCH 1
#define VD_CGLA_VERSION       ((VD_CGLA_VERSION_MAJOR << 16) | (VD_CGLA_VERSION_MINOR << 8) | (VD_CGLA_VERSION_PATCH))

#ifndef VD_H
#error "vd_cgla.h requires vd.h"
#endif // !VD_H

/* ----FORMATS------------------------------------------------------------------------------------------------------- */
#ifndef VD_CGLA_FORMAT_NAME
#define VD_CGLA_FORMAT_NAME(f) VD_STRING_JOIN2(VD_CGLA_,f)
#endif // !VD_CGLA_FORMAT_NAME

#ifndef VD_CGLA_FORMAT_TYPE
#define VD_CGLA_FORMAT_TYPE VdCGLAFormat
#endif // !VD_CGLA_FORMAT_TYPE

#define VD_CGLA_ALL_FORMATS \
    X(FORMAT_UNKNOWN) \
    X(FORMAT_R4G4_UNORM_PACK8) \
    X(FORMAT_R4G4B4A4_UNORM_PACK16) \
    X(FORMAT_B4G4R4A4_UNORM_PACK16) \
    X(FORMAT_R5G6B5_UNORM_PACK16) \
    X(FORMAT_B5G6R5_UNORM_PACK16) \
    X(FORMAT_R5G5B5A1_UNORM_PACK16) \
    X(FORMAT_B5G5R5A1_UNORM_PACK16) \
    X(FORMAT_A1R5G5B5_UNORM_PACK16) \
    X(FORMAT_R8_UNORM) \
    X(FORMAT_R8_SNORM) \
    X(FORMAT_R8_USCALED) \
    X(FORMAT_R8_SSCALED) \
    X(FORMAT_R8_UINT) \
    X(FORMAT_R8_SINT) \
    X(FORMAT_R8_SRGB) \
    X(FORMAT_R8G8_UNORM) \
    X(FORMAT_R8G8_SNORM) \
    X(FORMAT_R8G8_USCALED) \
    X(FORMAT_R8G8_SSCALED) \
    X(FORMAT_R8G8_UINT) \
    X(FORMAT_R8G8_SINT) \
    X(FORMAT_R8G8_SRGB) \
    X(FORMAT_R8G8B8_UNORM) \
    X(FORMAT_R8G8B8_SNORM) \
    X(FORMAT_R8G8B8_USCALED) \
    X(FORMAT_R8G8B8_SSCALED) \
    X(FORMAT_R8G8B8_UINT) \
    X(FORMAT_R8G8B8_SINT) \
    X(FORMAT_R8G8B8_SRGB) \
    X(FORMAT_B8G8R8_UNORM) \
    X(FORMAT_B8G8R8_SNORM) \
    X(FORMAT_B8G8R8_USCALED) \
    X(FORMAT_B8G8R8_SSCALED) \
    X(FORMAT_B8G8R8_UINT) \
    X(FORMAT_B8G8R8_SINT) \
    X(FORMAT_B8G8R8_SRGB) \
    X(FORMAT_R8G8B8A8_UNORM) \
    X(FORMAT_R8G8B8A8_SNORM) \
    X(FORMAT_R8G8B8A8_USCALED) \
    X(FORMAT_R8G8B8A8_SSCALED) \
    X(FORMAT_R8G8B8A8_UINT) \
    X(FORMAT_R8G8B8A8_SINT) \
    X(FORMAT_R8G8B8A8_SRGB) \
    X(FORMAT_B8G8R8A8_UNORM) \
    X(FORMAT_B8G8R8A8_SNORM) \
    X(FORMAT_B8G8R8A8_USCALED) \
    X(FORMAT_B8G8R8A8_SSCALED) \
    X(FORMAT_B8G8R8A8_UINT) \
    X(FORMAT_B8G8R8A8_SINT) \
    X(FORMAT_B8G8R8A8_SRGB) \
    X(FORMAT_A8B8G8R8_UNORM_PACK32) \
    X(FORMAT_A8B8G8R8_SNORM_PACK32) \
    X(FORMAT_A8B8G8R8_USCALED_PACK32) \
    X(FORMAT_A8B8G8R8_SSCALED_PACK32) \
    X(FORMAT_A8B8G8R8_UINT_PACK32) \
    X(FORMAT_A8B8G8R8_SINT_PACK32) \
    X(FORMAT_A8B8G8R8_SRGB_PACK32) \
    X(FORMAT_A2R10G10B10_UNORM_PACK32) \
    X(FORMAT_A2R10G10B10_SNORM_PACK32) \
    X(FORMAT_A2R10G10B10_USCALED_PACK32) \
    X(FORMAT_A2R10G10B10_SSCALED_PACK32) \
    X(FORMAT_A2R10G10B10_UINT_PACK32) \
    X(FORMAT_A2R10G10B10_SINT_PACK32) \
    X(FORMAT_A2B10G10R10_UNORM_PACK32) \
    X(FORMAT_A2B10G10R10_SNORM_PACK32) \
    X(FORMAT_A2B10G10R10_USCALED_PACK32) \
    X(FORMAT_A2B10G10R10_SSCALED_PACK32) \
    X(FORMAT_A2B10G10R10_UINT_PACK32) \
    X(FORMAT_A2B10G10R10_SINT_PACK32) \
    X(FORMAT_R16_UNORM) \
    X(FORMAT_R16_SNORM) \
    X(FORMAT_R16_USCALED) \
    X(FORMAT_R16_SSCALED) \
    X(FORMAT_R16_UINT) \
    X(FORMAT_R16_SINT) \
    X(FORMAT_R16_SFLOAT) \
    X(FORMAT_R16G16_UNORM) \
    X(FORMAT_R16G16_SNORM) \
    X(FORMAT_R16G16_USCALED) \
    X(FORMAT_R16G16_SSCALED) \
    X(FORMAT_R16G16_UINT) \
    X(FORMAT_R16G16_SINT) \
    X(FORMAT_R16G16_SFLOAT) \
    X(FORMAT_R16G16B16_UNORM) \
    X(FORMAT_R16G16B16_SNORM) \
    X(FORMAT_R16G16B16_USCALED) \
    X(FORMAT_R16G16B16_SSCALED) \
    X(FORMAT_R16G16B16_UINT) \
    X(FORMAT_R16G16B16_SINT) \
    X(FORMAT_R16G16B16_SFLOAT) \
    X(FORMAT_R16G16B16A16_UNORM) \
    X(FORMAT_R16G16B16A16_SNORM) \
    X(FORMAT_R16G16B16A16_USCALED) \
    X(FORMAT_R16G16B16A16_SSCALED) \
    X(FORMAT_R16G16B16A16_UINT) \
    X(FORMAT_R16G16B16A16_SINT) \
    X(FORMAT_R16G16B16A16_SFLOAT) \
    X(FORMAT_R32_UINT) \
    X(FORMAT_R32_SINT) \
    X(FORMAT_R32_SFLOAT) \
    X(FORMAT_R32G32_UINT) \
    X(FORMAT_R32G32_SINT) \
    X(FORMAT_R32G32_SFLOAT) \
    X(FORMAT_R32G32B32_UINT) \
    X(FORMAT_R32G32B32_SINT) \
    X(FORMAT_R32G32B32_SFLOAT) \
    X(FORMAT_R32G32B32A32_UINT) \
    X(FORMAT_R32G32B32A32_SINT) \
    X(FORMAT_R32G32B32A32_SFLOAT) \
    X(FORMAT_R64_UINT) \
    X(FORMAT_R64_SINT) \
    X(FORMAT_R64_SFLOAT) \
    X(FORMAT_R64G64_UINT) \
    X(FORMAT_R64G64_SINT) \
    X(FORMAT_R64G64_SFLOAT) \
    X(FORMAT_R64G64B64_UINT) \
    X(FORMAT_R64G64B64_SINT) \
    X(FORMAT_R64G64B64_SFLOAT) \
    X(FORMAT_R64G64B64A64_UINT) \
    X(FORMAT_R64G64B64A64_SINT) \
    X(FORMAT_R64G64B64A64_SFLOAT) \
    X(FORMAT_B10G11R11_UFLOAT_PACK32) \
    X(FORMAT_E5B9G9R9_UFLOAT_PACK32) \
    X(FORMAT_D16_UNORM) \
    X(FORMAT_X8_D24_UNORM_PACK32) \
    X(FORMAT_D32_SFLOAT) \
    X(FORMAT_S8_UINT) \
    X(FORMAT_D16_UNORM_S8_UINT) \
    X(FORMAT_D24_UNORM_S8_UINT) \
    X(FORMAT_D32_SFLOAT_S8_UINT) \
    X(FORMAT_BC1_RGB_UNORM_BLOCK) \
    X(FORMAT_BC1_RGB_SRGB_BLOCK) \
    X(FORMAT_BC1_RGBA_UNORM_BLOCK) \
    X(FORMAT_BC1_RGBA_SRGB_BLOCK) \
    X(FORMAT_BC2_UNORM_BLOCK) \
    X(FORMAT_BC2_SRGB_BLOCK) \
    X(FORMAT_BC3_UNORM_BLOCK) \
    X(FORMAT_BC3_SRGB_BLOCK) \
    X(FORMAT_BC4_UNORM_BLOCK) \
    X(FORMAT_BC4_SNORM_BLOCK) \
    X(FORMAT_BC5_UNORM_BLOCK) \
    X(FORMAT_BC5_SNORM_BLOCK) \
    X(FORMAT_BC6H_UFLOAT_BLOCK) \
    X(FORMAT_BC6H_SFLOAT_BLOCK) \
    X(FORMAT_BC7_UNORM_BLOCK) \
    X(FORMAT_BC7_SRGB_BLOCK) \
    X(FORMAT_ETC2_R8G8B8_UNORM_BLOCK) \
    X(FORMAT_ETC2_R8G8B8_SRGB_BLOCK) \
    X(FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK) \
    X(FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK) \
    X(FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK) \
    X(FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK) \
    X(FORMAT_EAC_R11_UNORM_BLOCK) \
    X(FORMAT_EAC_R11_SNORM_BLOCK) \
    X(FORMAT_EAC_R11G11_UNORM_BLOCK) \
    X(FORMAT_EAC_R11G11_SNORM_BLOCK) \
    X(FORMAT_ASTC_4x4_UNORM_BLOCK) \
    X(FORMAT_ASTC_4x4_SRGB_BLOCK) \
    X(FORMAT_ASTC_5x4_UNORM_BLOCK) \
    X(FORMAT_ASTC_5x4_SRGB_BLOCK) \
    X(FORMAT_ASTC_5x5_UNORM_BLOCK) \
    X(FORMAT_ASTC_5x5_SRGB_BLOCK) \
    X(FORMAT_ASTC_6x5_UNORM_BLOCK) \
    X(FORMAT_ASTC_6x5_SRGB_BLOCK) \
    X(FORMAT_ASTC_6x6_UNORM_BLOCK) \
    X(FORMAT_ASTC_6x6_SRGB_BLOCK) \
    X(FORMAT_ASTC_8x5_UNORM_BLOCK) \
    X(FORMAT_ASTC_8x5_SRGB_BLOCK) \
    X(FORMAT_ASTC_8x6_UNORM_BLOCK) \
    X(FORMAT_ASTC_8x6_SRGB_BLOCK) \
    X(FORMAT_ASTC_8x8_UNORM_BLOCK) \
    X(FORMAT_ASTC_8x8_SRGB_BLOCK) \
    X(FORMAT_ASTC_10x5_UNORM_BLOCK) \
    X(FORMAT_ASTC_10x5_SRGB_BLOCK) \
    X(FORMAT_ASTC_10x6_UNORM_BLOCK) \
    X(FORMAT_ASTC_10x6_SRGB_BLOCK) \
    X(FORMAT_ASTC_10x8_UNORM_BLOCK) \
    X(FORMAT_ASTC_10x8_SRGB_BLOCK) \
    X(FORMAT_ASTC_10x10_UNORM_BLOCK) \
    X(FORMAT_ASTC_10x10_SRGB_BLOCK) \
    X(FORMAT_ASTC_12x10_UNORM_BLOCK) \
    X(FORMAT_ASTC_12x10_SRGB_BLOCK) \
    X(FORMAT_ASTC_12x12_UNORM_BLOCK) \
    X(FORMAT_ASTC_12x12_SRGB_BLOCK) \
    X(FORMAT_G8B8G8R8_422_UNORM) \
    X(FORMAT_B8G8R8G8_422_UNORM) \
    X(FORMAT_G8_B8_R8_3PLANE_420_UNORM) \
    X(FORMAT_G8_B8R8_2PLANE_420_UNORM) \
    X(FORMAT_G8_B8_R8_3PLANE_422_UNORM) \
    X(FORMAT_G8_B8R8_2PLANE_422_UNORM) \
    X(FORMAT_G8_B8_R8_3PLANE_444_UNORM) \
    X(FORMAT_R10X6_UNORM_PACK16) \
    X(FORMAT_R10X6G10X6_UNORM_2PACK16) \
    X(FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16) \
    X(FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16) \
    X(FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16) \
    X(FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16) \
    X(FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16) \
    X(FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16) \
    X(FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16) \
    X(FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16) \
    X(FORMAT_R12X4_UNORM_PACK16) \
    X(FORMAT_R12X4G12X4_UNORM_2PACK16) \
    X(FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16) \
    X(FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16) \
    X(FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16) \
    X(FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16) \
    X(FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16) \
    X(FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16) \
    X(FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16) \
    X(FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16) \
    X(FORMAT_G16B16G16R16_422_UNORM) \
    X(FORMAT_B16G16R16G16_422_UNORM) \
    X(FORMAT_G16_B16_R16_3PLANE_420_UNORM) \
    X(FORMAT_G16_B16R16_2PLANE_420_UNORM) \
    X(FORMAT_G16_B16_R16_3PLANE_422_UNORM) \
    X(FORMAT_G16_B16R16_2PLANE_422_UNORM) \
    X(FORMAT_G16_B16_R16_3PLANE_444_UNORM) \
    X(FORMAT_G8_B8R8_2PLANE_444_UNORM) \
    X(FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16) \
    X(FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16) \
    X(FORMAT_G16_B16R16_2PLANE_444_UNORM) \
    X(FORMAT_A4R4G4B4_UNORM_PACK16) \
    X(FORMAT_A4B4G4R4_UNORM_PACK16) \
    X(FORMAT_ASTC_4x4_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_5x4_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_5x5_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_6x5_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_6x6_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_8x5_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_8x6_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_8x8_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_10x5_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_10x6_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_10x8_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_10x10_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_12x10_SFLOAT_BLOCK) \
    X(FORMAT_ASTC_12x12_SFLOAT_BLOCK) \
    X(FORMAT_A1B5G5R5_UNORM_PACK16) \
    X(FORMAT_A8_UNORM) \
    X(FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG) \
    X(FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG) \
    X(FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG) \
    X(FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG) \
    X(FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG) \
    X(FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG) \
    X(FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG) \
    X(FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG) \
    X(FORMAT_R8_BOOL_ARM) \
    X(FORMAT_R16G16_SFIXED5_NV) \
    X(FORMAT_R10X6_UINT_PACK16_ARM) \
    X(FORMAT_R10X6G10X6_UINT_2PACK16_ARM) \
    X(FORMAT_R10X6G10X6B10X6A10X6_UINT_4PACK16_ARM) \
    X(FORMAT_R12X4_UINT_PACK16_ARM) \
    X(FORMAT_R12X4G12X4_UINT_2PACK16_ARM) \
    X(FORMAT_R12X4G12X4B12X4A12X4_UINT_4PACK16_ARM) \
    X(FORMAT_R14X2_UINT_PACK16_ARM) \
    X(FORMAT_R14X2G14X2_UINT_2PACK16_ARM) \
    X(FORMAT_R14X2G14X2B14X2A14X2_UINT_4PACK16_ARM) \
    X(FORMAT_R14X2_UNORM_PACK16_ARM) \
    X(FORMAT_R14X2G14X2_UNORM_2PACK16_ARM) \
    X(FORMAT_R14X2G14X2B14X2A14X2_UNORM_4PACK16_ARM) \
    X(FORMAT_G14X2_B14X2R14X2_2PLANE_420_UNORM_3PACK16_ARM) \
    X(FORMAT_G14X2_B14X2R14X2_2PLANE_422_UNORM_3PACK16_ARM) \
    X(FORMAT_MAX)

typedef enum {
#define X(f) VD_CGLA_FORMAT_NAME(f),
    VD_CGLA_ALL_FORMATS
#undef X
} VD_CGLA_FORMAT_TYPE;

static VD_INLINE VdStr vd_cgla_format_to_str(VD_CGLA_FORMAT_TYPE type)
{
    static VdStr table[VD_CGLA_FORMAT_NAME(FORMAT_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_FORMATS
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_format_to_str  vd_cgla_format_to_str 
#endif

/* ----PRIMITIVE TOPOLOGIES------------------------------------------------------------------------------------------ */
#ifndef VD_CGLA_PRIMITIVE_TOPOLOGY_NAME
#define VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(f) VD_STRING_JOIN2(VD_CGLA_, f)
#endif // !VD_CGLA_PRIMITIVE_TOPOLOGY_NAME

#ifndef VD_CGLA_PRIMITIVE_TOPOLOGY_TYPE
#define VD_CGLA_PRIMITIVE_TOPOLOGY_TYPE VdCGLAPrimitiveTopology
#endif // !VD_CGLA_PRIMITIVE_TOPOLOGY_TYPE

#define VD_CGLA_ALL_PRIMITIVE_TOPOLOGIES \
    X(PRIMITIVE_TOPOLOGY_UNKNOWN) \
    X(PRIMITIVE_TOPOLOGY_POINT_LIST) \
    X(PRIMITIVE_TOPOLOGY_LINE_LIST) \
    X(PRIMITIVE_TOPOLOGY_LINE_STRIP) \
    X(PRIMITIVE_TOPOLOGY_TRIANGLE_LIST) \
    X(PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP) \
    X(PRIMITIVE_TOPOLOGY_TRIANGLE_FAN) \
    X(PRIMITIVE_TOPOLOGY_MAX)

typedef enum {
#define X(f) VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(f),
    VD_CGLA_ALL_PRIMITIVE_TOPOLOGIES
#undef X
} VD_CGLA_PRIMITIVE_TOPOLOGY_TYPE;

static VD_INLINE VdStr vd_cgla_primitive_topology_to_str(VD_CGLA_PRIMITIVE_TOPOLOGY_TYPE type)
{
    static VdStr table[VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_PRIMITIVE_TOPOLOGIES
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_primitive_topology_to_str  vd_cgla_primitive_topology_to_str 
#endif // VD_MACRO_ABBREVIATIONS

/* ----POLYGON MODES------------------------------------------------------------------------------------------------- */
#ifndef VD_CGLA_POLYGON_MODE_NAME
#define VD_CGLA_POLYGON_MODE_NAME(f) VD_STRING_JOIN2(VD_CGLA_, f)
#endif // !VD_CGLA_POLYGON_MODE_NAME

#ifndef VD_CGLA_POLYGON_MODE_TYPE
#define VD_CGLA_POLYGON_MODE_TYPE VdCGLAPolygonMode
#endif // !VD_CGLA_POLYGON_MODE_TYPE

#define VD_CGLA_ALL_POLYGON_MODES \
    X(POLYGON_MODE_UNKNOWN) \
    X(POLYGON_MODE_FILL) \
    X(POLYGON_MODE_LINE) \
    X(POLYGON_MODE_POINT) \
    X(POLYGON_MODE_MAX)

typedef enum {
#define X(f) VD_CGLA_POLYGON_MODE_NAME(f),
    VD_CGLA_ALL_POLYGON_MODES
#undef X
} VD_CGLA_POLYGON_MODE_TYPE;

static VD_INLINE VdStr vd_cgla_polygon_mode_to_str(VD_CGLA_POLYGON_MODE_TYPE type)
{
    static VdStr table[VD_CGLA_POLYGON_MODE_NAME(POLYGON_MODE_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_POLYGON_MODES
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_polygon_mode_to_str  vd_cgla_polygon_mode_to_str 
#endif // VD_MACRO_ABBREVIATIONS

/* ----CULL MODES---------------------------------------------------------------------------------------------------- */
#ifndef VD_CGLA_CULL_MODE_NAME
#define VD_CGLA_CULL_MODE_NAME(f) VD_STRING_JOIN2(VD_CGLA_,f)
#endif // !VD_CGLA_CULL_MODE_NAME

#ifndef VD_CGLA_CULL_MODE_TYPE
#define VD_CGLA_CULL_MODE_TYPE VdCGLACullMode
#endif // !VD_CGLA_CULL_MODE_TYPE

#define VD_CGLA_ALL_CULL_MODES \
    X(CULL_MODE_UNKNOWN) \
    X(CULL_MODE_NONE) \
    X(CULL_MODE_FRONT) \
    X(CULL_MODE_BACK) \
    X(CULL_MODE_FRONT_AND_BACK) \
    X(CULL_MODE_MAX)

typedef enum {
#define X(f) VD_CGLA_CULL_MODE_NAME(f),
    VD_CGLA_ALL_CULL_MODES
#undef X
} VD_CGLA_CULL_MODE_TYPE;

static VD_INLINE VdStr vd_cgla_cull_mode_to_str(VD_CGLA_CULL_MODE_TYPE type)
{
    static VdStr table[VD_CGLA_CULL_MODE_NAME(CULL_MODE_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_CULL_MODES
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_cull_mode_to_str  vd_cgla_cull_mode_to_str 
#endif // VD_MACRO_ABBREVIATIONS

/* ----FRONT FACES--------------------------------------------------------------------------------------------------- */
#ifndef VD_CGLA_FRONT_FACE_NAME
#define VD_CGLA_FRONT_FACE_NAME(f) VD_STRING_JOIN2(VD_CGLA_,f)
#endif // !VD_CGLA_FRONT_FACE_NAME

#ifndef VD_CGLA_FRONT_FACE_TYPE
#define VD_CGLA_FRONT_FACE_TYPE VdCGLAFrontFace
#endif // !VD_CGLA_FRONT_FACE_TYPE

#define VD_CGLA_ALL_FRONT_FACES \
    X(FRONT_FACE_UNKNOWN) \
    X(FRONT_FACE_COUNTER_CLOCKWISE) \
    X(FRONT_FACE_CLOCKWISE) \
    X(FRONT_FACE_MAX)

typedef enum {
#define X(f) VD_CGLA_FRONT_FACE_NAME(f),
    VD_CGLA_ALL_FRONT_FACES
#undef X
} VD_CGLA_FRONT_FACE_TYPE;

static VD_INLINE VdStr vd_cgla_front_face_to_str(VD_CGLA_FRONT_FACE_TYPE type)
{
    static VdStr table[VD_CGLA_FRONT_FACE_NAME(FRONT_FACE_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_FRONT_FACES
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_front_face_to_str  vd_cgla_front_face_to_str 
#endif // VD_MACRO_ABBREVIATIONS

/* ----COMPARE OPERATORS--------------------------------------------------------------------------------------------- */
#ifndef VD_CGLA_COMPARE_OPERATOR_NAME
#define VD_CGLA_COMPARE_OPERATOR_NAME(f) VD_STRING_JOIN2(VD_CGLA_,f)
#endif // !VD_CGLA_COMPARE_OPERATOR_NAME

#ifndef VD_CGLA_COMPARE_OPERATOR_TYPE
#define VD_CGLA_COMPARE_OPERATOR_TYPE VdCGLACompareOperator
#endif // !VD_CGLA_COMPARE_OPERATOR_TYPE

#define VD_CGLA_ALL_COMPARE_OPERATORS \
    X(COMPARE_OPERATOR_UNKNOWN)       \
    X(COMPARE_OPERATOR_NEVER)         \
    X(COMPARE_OPERATOR_LESS)          \
    X(COMPARE_OPERATOR_EQUAL)         \
    X(COMPARE_OPERATOR_LEQUAL)        \
    X(COMPARE_OPERATOR_GREATER)       \
    X(COMPARE_OPERATOR_GEQUAL)        \
    X(COMPARE_OPERATOR_ALWAYS)        \
    X(COMPARE_OPERATOR_MAX)

typedef enum {
#define X(f) VD_CGLA_COMPARE_OPERATOR_NAME(f),
    VD_CGLA_ALL_COMPARE_OPERATORS
#undef X
} VD_CGLA_COMPARE_OPERATOR_TYPE;

static VD_INLINE VdStr vd_cgla_depth_compare_operator_to_str(VD_CGLA_COMPARE_OPERATOR_TYPE type)
{
    static VdStr table[VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_COMPARE_OPERATORS
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_depth_compare_operator_to_str  vd_cgla_depth_compare_operator_to_str 
#endif // VD_MACRO_ABBREVIATIONS

/* ----IMAGE LAYOUTS------------------------------------------------------------------------------------------------- */
#ifndef VD_CGLA_IMAGE_LAYOUT_NAME
#define VD_CGLA_IMAGE_LAYOUT_NAME(f) VD_STRING_JOIN2(VD_CGLA_, f)
#endif // !VD_CGLA_IMAGE_LAYOUT_NAME

#ifndef VD_CGLA_IMAGE_LAYOUT_TYPE
#define VD_CGLA_IMAGE_LAYOUT_TYPE VdCGLAImageLayout
#endif // !VD_CGLA_IMAGE_LAYOUT_TYPE

#define VD_CGLA_ALL_IMAGE_LAYOUTS                              \
    X(IMAGE_LAYOUT_INVALID)                                    \
    X(IMAGE_LAYOUT_UNDEFINED)                                  \
    X(IMAGE_LAYOUT_GENERAL)                                    \
    X(IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL)                   \
    X(IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL)           \
    X(IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL)            \
    X(IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL)                   \
    X(IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL)                       \
    X(IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL)                       \
    X(IMAGE_LAYOUT_PREINITIALIZED)                             \
    X(IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL) \
    X(IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL) \
    X(IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL)                   \
    X(IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL)                    \
    X(IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL)                 \
    X(IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL)                  \
    X(IMAGE_LAYOUT_READ_ONLY_OPTIMAL)                          \
    X(IMAGE_LAYOUT_ATTACHMENT_OPTIMAL)                         \
    X(IMAGE_LAYOUT_RENDERING_LOCAL_READ)                       \
    X(IMAGE_LAYOUT_PRESENT_SRC)                                \
    X(IMAGE_LAYOUT_VIDEO_DECODE_DST)                           \
    X(IMAGE_LAYOUT_VIDEO_DECODE_SRC)                           \
    X(IMAGE_LAYOUT_VIDEO_DECODE_DPB)                           \
    X(IMAGE_LAYOUT_MAX)

typedef enum {
#define X(f) VD_CGLA_IMAGE_LAYOUT_NAME(f),
    VD_CGLA_ALL_IMAGE_LAYOUTS
#undef X
} VD_CGLA_IMAGE_LAYOUT_TYPE;

static VD_INLINE VdStr vd_cgla_image_layout_to_str(VD_CGLA_IMAGE_LAYOUT_TYPE type)
{
    static VdStr table[VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_MAX) + 1] = {
#define X(f) VD_LIT_INLINE(#f),
        VD_CGLA_ALL_IMAGE_LAYOUTS
#undef X
    };
    return table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_image_layout_to_str  vd_cgla_image_layout_to_str 
#endif // VD_MACRO_ABBREVIATIONS

#endif // !VD_CGLA_H

#ifdef VD_CGLA_VK_IMPL
#ifndef VULKAN_CORE_H_
#warning "vd_cgla.h with VD_CGLA_VK_IMPL requires vulkan/vulkan.h"
#endif

/* ----VK FORMAT----------------------------------------------------------------------------------------------------- */
static VD_INLINE VkFormat vd_cgla_format_to_vk_format(VD_CGLA_FORMAT_TYPE format)
{
    static VkFormat translation_table[VD_CGLA_FORMAT_NAME(FORMAT_MAX)] = {
        [VD_CGLA_FORMAT_NAME(FORMAT_UNKNOWN)]                                       = VK_FORMAT_UNDEFINED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R4G4_UNORM_PACK8)]                              = VK_FORMAT_R4G4_UNORM_PACK8,
        [VD_CGLA_FORMAT_NAME(FORMAT_R4G4B4A4_UNORM_PACK16)]                         = VK_FORMAT_R4G4B4A4_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_B4G4R4A4_UNORM_PACK16)]                         = VK_FORMAT_B4G4R4A4_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R5G6B5_UNORM_PACK16)]                           = VK_FORMAT_R5G6B5_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_B5G6R5_UNORM_PACK16)]                           = VK_FORMAT_B5G6R5_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R5G5B5A1_UNORM_PACK16)]                         = VK_FORMAT_R5G5B5A1_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_B5G5R5A1_UNORM_PACK16)]                         = VK_FORMAT_B5G5R5A1_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_A1R5G5B5_UNORM_PACK16)]                         = VK_FORMAT_A1R5G5B5_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_UNORM)]                                      = VK_FORMAT_R8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_SNORM)]                                      = VK_FORMAT_R8_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_USCALED)]                                    = VK_FORMAT_R8_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_SSCALED)]                                    = VK_FORMAT_R8_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_UINT)]                                       = VK_FORMAT_R8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_SINT)]                                       = VK_FORMAT_R8_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_SRGB)]                                       = VK_FORMAT_R8_SRGB,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_UNORM)]                                    = VK_FORMAT_R8G8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_SNORM)]                                    = VK_FORMAT_R8G8_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_USCALED)]                                  = VK_FORMAT_R8G8_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_SSCALED)]                                  = VK_FORMAT_R8G8_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_UINT)]                                     = VK_FORMAT_R8G8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_SINT)]                                     = VK_FORMAT_R8G8_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8_SRGB)]                                     = VK_FORMAT_R8G8_SRGB,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_UNORM)]                                  = VK_FORMAT_R8G8B8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_SNORM)]                                  = VK_FORMAT_R8G8B8_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_USCALED)]                                = VK_FORMAT_R8G8B8_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_SSCALED)]                                = VK_FORMAT_R8G8B8_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_UINT)]                                   = VK_FORMAT_R8G8B8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_SINT)]                                   = VK_FORMAT_R8G8B8_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8_SRGB)]                                   = VK_FORMAT_R8G8B8_SRGB,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_UNORM)]                                  = VK_FORMAT_B8G8R8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_SNORM)]                                  = VK_FORMAT_B8G8R8_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_USCALED)]                                = VK_FORMAT_B8G8R8_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_SSCALED)]                                = VK_FORMAT_B8G8R8_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_UINT)]                                   = VK_FORMAT_B8G8R8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_SINT)]                                   = VK_FORMAT_B8G8R8_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8_SRGB)]                                   = VK_FORMAT_B8G8R8_SRGB,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_UNORM)]                                = VK_FORMAT_R8G8B8A8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_SNORM)]                                = VK_FORMAT_R8G8B8A8_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_USCALED)]                              = VK_FORMAT_R8G8B8A8_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_SSCALED)]                              = VK_FORMAT_R8G8B8A8_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_UINT)]                                 = VK_FORMAT_R8G8B8A8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_SINT)]                                 = VK_FORMAT_R8G8B8A8_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8G8B8A8_SRGB)]                                 = VK_FORMAT_R8G8B8A8_SRGB,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_UNORM)]                                = VK_FORMAT_B8G8R8A8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_SNORM)]                                = VK_FORMAT_B8G8R8A8_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_USCALED)]                              = VK_FORMAT_B8G8R8A8_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_SSCALED)]                              = VK_FORMAT_B8G8R8A8_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_UINT)]                                 = VK_FORMAT_B8G8R8A8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_SINT)]                                 = VK_FORMAT_B8G8R8A8_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8A8_SRGB)]                                 = VK_FORMAT_B8G8R8A8_SRGB,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_UNORM_PACK32)]                         = VK_FORMAT_A8B8G8R8_UNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_SNORM_PACK32)]                         = VK_FORMAT_A8B8G8R8_SNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_USCALED_PACK32)]                       = VK_FORMAT_A8B8G8R8_USCALED_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_SSCALED_PACK32)]                       = VK_FORMAT_A8B8G8R8_SSCALED_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_UINT_PACK32)]                          = VK_FORMAT_A8B8G8R8_UINT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_SINT_PACK32)]                          = VK_FORMAT_A8B8G8R8_SINT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8B8G8R8_SRGB_PACK32)]                          = VK_FORMAT_A8B8G8R8_SRGB_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2R10G10B10_UNORM_PACK32)]                      = VK_FORMAT_A2R10G10B10_UNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2R10G10B10_SNORM_PACK32)]                      = VK_FORMAT_A2R10G10B10_SNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2R10G10B10_USCALED_PACK32)]                    = VK_FORMAT_A2R10G10B10_USCALED_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2R10G10B10_SSCALED_PACK32)]                    = VK_FORMAT_A2R10G10B10_SSCALED_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2R10G10B10_UINT_PACK32)]                       = VK_FORMAT_A2R10G10B10_UINT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2R10G10B10_SINT_PACK32)]                       = VK_FORMAT_A2R10G10B10_SINT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2B10G10R10_UNORM_PACK32)]                      = VK_FORMAT_A2B10G10R10_UNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2B10G10R10_SNORM_PACK32)]                      = VK_FORMAT_A2B10G10R10_SNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2B10G10R10_USCALED_PACK32)]                    = VK_FORMAT_A2B10G10R10_USCALED_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2B10G10R10_SSCALED_PACK32)]                    = VK_FORMAT_A2B10G10R10_SSCALED_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2B10G10R10_UINT_PACK32)]                       = VK_FORMAT_A2B10G10R10_UINT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_A2B10G10R10_SINT_PACK32)]                       = VK_FORMAT_A2B10G10R10_SINT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_UNORM)]                                     = VK_FORMAT_R16_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_SNORM)]                                     = VK_FORMAT_R16_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_USCALED)]                                   = VK_FORMAT_R16_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_SSCALED)]                                   = VK_FORMAT_R16_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_UINT)]                                      = VK_FORMAT_R16_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_SINT)]                                      = VK_FORMAT_R16_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16_SFLOAT)]                                    = VK_FORMAT_R16_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_UNORM)]                                  = VK_FORMAT_R16G16_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_SNORM)]                                  = VK_FORMAT_R16G16_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_USCALED)]                                = VK_FORMAT_R16G16_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_SSCALED)]                                = VK_FORMAT_R16G16_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_UINT)]                                   = VK_FORMAT_R16G16_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_SINT)]                                   = VK_FORMAT_R16G16_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_SFLOAT)]                                 = VK_FORMAT_R16G16_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_UNORM)]                               = VK_FORMAT_R16G16B16_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_SNORM)]                               = VK_FORMAT_R16G16B16_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_USCALED)]                             = VK_FORMAT_R16G16B16_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_SSCALED)]                             = VK_FORMAT_R16G16B16_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_UINT)]                                = VK_FORMAT_R16G16B16_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_SINT)]                                = VK_FORMAT_R16G16B16_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16_SFLOAT)]                              = VK_FORMAT_R16G16B16_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_UNORM)]                            = VK_FORMAT_R16G16B16A16_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_SNORM)]                            = VK_FORMAT_R16G16B16A16_SNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_USCALED)]                          = VK_FORMAT_R16G16B16A16_USCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_SSCALED)]                          = VK_FORMAT_R16G16B16A16_SSCALED,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_UINT)]                             = VK_FORMAT_R16G16B16A16_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_SINT)]                             = VK_FORMAT_R16G16B16A16_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16B16A16_SFLOAT)]                           = VK_FORMAT_R16G16B16A16_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32_UINT)]                                      = VK_FORMAT_R32_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32_SINT)]                                      = VK_FORMAT_R32_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32_SFLOAT)]                                    = VK_FORMAT_R32_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32_UINT)]                                   = VK_FORMAT_R32G32_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32_SINT)]                                   = VK_FORMAT_R32G32_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32_SFLOAT)]                                 = VK_FORMAT_R32G32_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32B32_UINT)]                                = VK_FORMAT_R32G32B32_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32B32_SINT)]                                = VK_FORMAT_R32G32B32_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32B32_SFLOAT)]                              = VK_FORMAT_R32G32B32_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32B32A32_UINT)]                             = VK_FORMAT_R32G32B32A32_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32B32A32_SINT)]                             = VK_FORMAT_R32G32B32A32_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R32G32B32A32_SFLOAT)]                           = VK_FORMAT_R32G32B32A32_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64_UINT)]                                      = VK_FORMAT_R64_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64_SINT)]                                      = VK_FORMAT_R64_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64_SFLOAT)]                                    = VK_FORMAT_R64_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64_UINT)]                                   = VK_FORMAT_R64G64_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64_SINT)]                                   = VK_FORMAT_R64G64_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64_SFLOAT)]                                 = VK_FORMAT_R64G64_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64B64_UINT)]                                = VK_FORMAT_R64G64B64_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64B64_SINT)]                                = VK_FORMAT_R64G64B64_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64B64_SFLOAT)]                              = VK_FORMAT_R64G64B64_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64B64A64_UINT)]                             = VK_FORMAT_R64G64B64A64_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64B64A64_SINT)]                             = VK_FORMAT_R64G64B64A64_SINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_R64G64B64A64_SFLOAT)]                           = VK_FORMAT_R64G64B64A64_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_B10G11R11_UFLOAT_PACK32)]                       = VK_FORMAT_B10G11R11_UFLOAT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_E5B9G9R9_UFLOAT_PACK32)]                        = VK_FORMAT_E5B9G9R9_UFLOAT_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_D16_UNORM)]                                     = VK_FORMAT_D16_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_X8_D24_UNORM_PACK32)]                           = VK_FORMAT_X8_D24_UNORM_PACK32,
        [VD_CGLA_FORMAT_NAME(FORMAT_D32_SFLOAT)]                                    = VK_FORMAT_D32_SFLOAT,
        [VD_CGLA_FORMAT_NAME(FORMAT_S8_UINT)]                                       = VK_FORMAT_S8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_D16_UNORM_S8_UINT)]                             = VK_FORMAT_D16_UNORM_S8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_D24_UNORM_S8_UINT)]                             = VK_FORMAT_D24_UNORM_S8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_D32_SFLOAT_S8_UINT)]                            = VK_FORMAT_D32_SFLOAT_S8_UINT,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC1_RGB_UNORM_BLOCK)]                           = VK_FORMAT_BC1_RGB_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC1_RGB_SRGB_BLOCK)]                            = VK_FORMAT_BC1_RGB_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC1_RGBA_UNORM_BLOCK)]                          = VK_FORMAT_BC1_RGBA_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC1_RGBA_SRGB_BLOCK)]                           = VK_FORMAT_BC1_RGBA_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC2_UNORM_BLOCK)]                               = VK_FORMAT_BC2_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC2_SRGB_BLOCK)]                                = VK_FORMAT_BC2_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC3_UNORM_BLOCK)]                               = VK_FORMAT_BC3_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC3_SRGB_BLOCK)]                                = VK_FORMAT_BC3_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC4_UNORM_BLOCK)]                               = VK_FORMAT_BC4_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC4_SNORM_BLOCK)]                               = VK_FORMAT_BC4_SNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC5_UNORM_BLOCK)]                               = VK_FORMAT_BC5_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC5_SNORM_BLOCK)]                               = VK_FORMAT_BC5_SNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC6H_UFLOAT_BLOCK)]                             = VK_FORMAT_BC6H_UFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC6H_SFLOAT_BLOCK)]                             = VK_FORMAT_BC6H_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC7_UNORM_BLOCK)]                               = VK_FORMAT_BC7_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_BC7_SRGB_BLOCK)]                                = VK_FORMAT_BC7_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ETC2_R8G8B8_UNORM_BLOCK)]                       = VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ETC2_R8G8B8_SRGB_BLOCK)]                        = VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK)]                     = VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK)]                      = VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK)]                     = VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK)]                      = VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_EAC_R11_UNORM_BLOCK)]                           = VK_FORMAT_EAC_R11_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_EAC_R11_SNORM_BLOCK)]                           = VK_FORMAT_EAC_R11_SNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_EAC_R11G11_UNORM_BLOCK)]                        = VK_FORMAT_EAC_R11G11_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_EAC_R11G11_SNORM_BLOCK)]                        = VK_FORMAT_EAC_R11G11_SNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_4x4_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_4x4_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_4x4_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_4x4_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_5x4_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_5x4_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_5x4_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_5x4_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_5x5_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_5x5_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_5x5_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_5x5_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_6x5_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_6x5_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_6x5_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_6x5_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_6x6_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_6x6_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_6x6_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_6x6_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x5_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_8x5_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x5_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_8x5_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x6_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_8x6_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x6_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_8x6_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x8_UNORM_BLOCK)]                          = VK_FORMAT_ASTC_8x8_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x8_SRGB_BLOCK)]                           = VK_FORMAT_ASTC_8x8_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x5_UNORM_BLOCK)]                         = VK_FORMAT_ASTC_10x5_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x5_SRGB_BLOCK)]                          = VK_FORMAT_ASTC_10x5_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x6_UNORM_BLOCK)]                         = VK_FORMAT_ASTC_10x6_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x6_SRGB_BLOCK)]                          = VK_FORMAT_ASTC_10x6_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x8_UNORM_BLOCK)]                         = VK_FORMAT_ASTC_10x8_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x8_SRGB_BLOCK)]                          = VK_FORMAT_ASTC_10x8_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x10_UNORM_BLOCK)]                        = VK_FORMAT_ASTC_10x10_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x10_SRGB_BLOCK)]                         = VK_FORMAT_ASTC_10x10_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_12x10_UNORM_BLOCK)]                        = VK_FORMAT_ASTC_12x10_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_12x10_SRGB_BLOCK)]                         = VK_FORMAT_ASTC_12x10_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_12x12_UNORM_BLOCK)]                        = VK_FORMAT_ASTC_12x12_UNORM_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_12x12_SRGB_BLOCK)]                         = VK_FORMAT_ASTC_12x12_SRGB_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8B8G8R8_422_UNORM)]                            = VK_FORMAT_G8B8G8R8_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_B8G8R8G8_422_UNORM)]                            = VK_FORMAT_B8G8R8G8_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8_B8_R8_3PLANE_420_UNORM)]                     = VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8_B8R8_2PLANE_420_UNORM)]                      = VK_FORMAT_G8_B8R8_2PLANE_420_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8_B8_R8_3PLANE_422_UNORM)]                     = VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8_B8R8_2PLANE_422_UNORM)]                      = VK_FORMAT_G8_B8R8_2PLANE_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8_B8_R8_3PLANE_444_UNORM)]                     = VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R10X6_UNORM_PACK16)]                            = VK_FORMAT_R10X6_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R10X6G10X6_UNORM_2PACK16)]                      = VK_FORMAT_R10X6G10X6_UNORM_2PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16)]            = VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16)]        = VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16)]        = VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16)]    = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16)]     = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16)]    = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16)]     = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16)]    = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R12X4_UNORM_PACK16)]                            = VK_FORMAT_R12X4_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R12X4G12X4_UNORM_2PACK16)]                      = VK_FORMAT_R12X4G12X4_UNORM_2PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16)]            = VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16)]        = VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16)]        = VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16)]    = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16)]     = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16)]    = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16)]     = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16)]    = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16B16G16R16_422_UNORM)]                        = VK_FORMAT_G16B16G16R16_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_B16G16R16G16_422_UNORM)]                        = VK_FORMAT_B16G16R16G16_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16_B16_R16_3PLANE_420_UNORM)]                  = VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16_B16R16_2PLANE_420_UNORM)]                   = VK_FORMAT_G16_B16R16_2PLANE_420_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16_B16_R16_3PLANE_422_UNORM)]                  = VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16_B16R16_2PLANE_422_UNORM)]                   = VK_FORMAT_G16_B16R16_2PLANE_422_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16_B16_R16_3PLANE_444_UNORM)]                  = VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G8_B8R8_2PLANE_444_UNORM)]                      = VK_FORMAT_G8_B8R8_2PLANE_444_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16)]     = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16)]     = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_G16_B16R16_2PLANE_444_UNORM)]                   = VK_FORMAT_G16_B16R16_2PLANE_444_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_A4R4G4B4_UNORM_PACK16)]                         = VK_FORMAT_A4R4G4B4_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_A4B4G4R4_UNORM_PACK16)]                         = VK_FORMAT_A4B4G4R4_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_4x4_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_5x4_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_5x5_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_6x5_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_6x6_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x5_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x6_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_8x8_SFLOAT_BLOCK)]                         = VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x5_SFLOAT_BLOCK)]                        = VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x6_SFLOAT_BLOCK)]                        = VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x8_SFLOAT_BLOCK)]                        = VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_10x10_SFLOAT_BLOCK)]                       = VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_12x10_SFLOAT_BLOCK)]                       = VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_ASTC_12x12_SFLOAT_BLOCK)]                       = VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK,
        [VD_CGLA_FORMAT_NAME(FORMAT_A1B5G5R5_UNORM_PACK16)]                         = VK_FORMAT_A1B5G5R5_UNORM_PACK16,
        [VD_CGLA_FORMAT_NAME(FORMAT_A8_UNORM)]                                      = VK_FORMAT_A8_UNORM,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG)]                   = VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG)]                   = VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG)]                   = VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG)]                   = VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG)]                    = VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG)]                    = VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG)]                    = VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG)]                    = VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG,
        [VD_CGLA_FORMAT_NAME(FORMAT_R8_BOOL_ARM)]                                   = VK_FORMAT_R8_BOOL_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R16G16_SFIXED5_NV)]                             = VK_FORMAT_R16G16_SFIXED5_NV,
        [VD_CGLA_FORMAT_NAME(FORMAT_R10X6_UINT_PACK16_ARM)]                         = VK_FORMAT_R10X6_UINT_PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R10X6G10X6_UINT_2PACK16_ARM)]                   = VK_FORMAT_R10X6G10X6_UINT_2PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R10X6G10X6B10X6A10X6_UINT_4PACK16_ARM)]         = VK_FORMAT_R10X6G10X6B10X6A10X6_UINT_4PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R12X4_UINT_PACK16_ARM)]                         = VK_FORMAT_R12X4_UINT_PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R12X4G12X4_UINT_2PACK16_ARM)]                   = VK_FORMAT_R12X4G12X4_UINT_2PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R12X4G12X4B12X4A12X4_UINT_4PACK16_ARM)]         = VK_FORMAT_R12X4G12X4B12X4A12X4_UINT_4PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R14X2_UINT_PACK16_ARM)]                         = VK_FORMAT_R14X2_UINT_PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R14X2G14X2_UINT_2PACK16_ARM)]                   = VK_FORMAT_R14X2G14X2_UINT_2PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R14X2G14X2B14X2A14X2_UINT_4PACK16_ARM)]         = VK_FORMAT_R14X2G14X2B14X2A14X2_UINT_4PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R14X2_UNORM_PACK16_ARM)]                        = VK_FORMAT_R14X2_UNORM_PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R14X2G14X2_UNORM_2PACK16_ARM)]                  = VK_FORMAT_R14X2G14X2_UNORM_2PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_R14X2G14X2B14X2A14X2_UNORM_4PACK16_ARM)]        = VK_FORMAT_R14X2G14X2B14X2A14X2_UNORM_4PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G14X2_B14X2R14X2_2PLANE_420_UNORM_3PACK16_ARM)] = VK_FORMAT_G14X2_B14X2R14X2_2PLANE_420_UNORM_3PACK16_ARM,
        [VD_CGLA_FORMAT_NAME(FORMAT_G14X2_B14X2R14X2_2PLANE_422_UNORM_3PACK16_ARM)] = VK_FORMAT_G14X2_B14X2R14X2_2PLANE_422_UNORM_3PACK16_ARM,
    };

    return translation_table[format];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_format_to_vk_format  vd_cgla_format_to_vk_format 
#endif // VD_MACRO_ABBREVIATIONS

/* ----VK PRIMITIVE TOPOLOGY----------------------------------------------------------------------------------------- */
static VD_INLINE VkPrimitiveTopology vd_cgla_primitive_topology_to_vk_primitive_topology(VD_CGLA_PRIMITIVE_TOPOLOGY_TYPE type)
{
    static VkPrimitiveTopology translation_table[VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_MAX)] = {
        [VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_POINT_LIST)]     = VK_PRIMITIVE_TOPOLOGY_POINT_LIST,
        [VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_LINE_LIST)]      = VK_PRIMITIVE_TOPOLOGY_LINE_LIST,
        [VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_LINE_STRIP)]     = VK_PRIMITIVE_TOPOLOGY_LINE_STRIP,
        [VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_TRIANGLE_LIST)]  = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        [VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP)] = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
        [VD_CGLA_PRIMITIVE_TOPOLOGY_NAME(PRIMITIVE_TOPOLOGY_TRIANGLE_FAN)]   = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN,
    };

    return translation_table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_primitive_topology_to_vk_primitive_topology  vd_cgla_primitive_topology_to_vk_primitive_topology 
#endif // VD_MACRO_ABBREVIATIONS

/* ----VK POLYGON MODE----------------------------------------------------------------------------------------------- */
static VD_INLINE VkPolygonMode vd_cgla_polygon_mode_to_vk_polygon_mode(VD_CGLA_POLYGON_MODE_TYPE type)
{
    static VkPolygonMode translation_table[VD_CGLA_POLYGON_MODE_NAME(POLYGON_MODE_MAX)] = {
        [VD_CGLA_POLYGON_MODE_NAME(POLYGON_MODE_FILL)]  = VK_POLYGON_MODE_FILL,
        [VD_CGLA_POLYGON_MODE_NAME(POLYGON_MODE_LINE)]  = VK_POLYGON_MODE_LINE,
        [VD_CGLA_POLYGON_MODE_NAME(POLYGON_MODE_POINT)] = VK_POLYGON_MODE_POINT,
    };

    return translation_table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_polygon_mode_to_vk_polygon_mode  vd_cgla_polygon_mode_to_vk_polygon_mode 
#endif // VD_MACRO_ABBREVIATIONS

/* ----VK CULL MODE FLAGS-------------------------------------------------------------------------------------------- */
static VD_INLINE VkCullModeFlags vd_cgla_cull_mode_to_vk_cull_mode_flags(VD_CGLA_CULL_MODE_TYPE type)
{
    static VkCullModeFlags translation_table[VD_CGLA_CULL_MODE_NAME(CULL_MODE_MAX)] = {
        [VD_CGLA_CULL_MODE_NAME(CULL_MODE_NONE)]           = VK_CULL_MODE_NONE,
        [VD_CGLA_CULL_MODE_NAME(CULL_MODE_FRONT)]          = VK_CULL_MODE_FRONT_BIT,
        [VD_CGLA_CULL_MODE_NAME(CULL_MODE_BACK)]           = VK_CULL_MODE_BACK_BIT,
        [VD_CGLA_CULL_MODE_NAME(CULL_MODE_FRONT_AND_BACK)] = VK_CULL_MODE_FRONT_AND_BACK,
    };

    return translation_table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_cull_mode_to_vk_cull_mode_flags  vd_cgla_cull_mode_to_vk_cull_mode_flags 
#endif // VD_MACRO_ABBREVIATIONS

/* ----VK FRONT FACE------------------------------------------------------------------------------------------------- */
static VD_INLINE VkFrontFace vd_cgla_front_face_to_vk_front_face(VD_CGLA_FRONT_FACE_TYPE type)
{
    static VkFrontFace translation_table[VD_CGLA_FRONT_FACE_NAME(FRONT_FACE_MAX)] = {
        [VD_CGLA_FRONT_FACE_NAME(FRONT_FACE_COUNTER_CLOCKWISE)] = VK_FRONT_FACE_COUNTER_CLOCKWISE,
        [VD_CGLA_FRONT_FACE_NAME(FRONT_FACE_CLOCKWISE)]         = VK_FRONT_FACE_CLOCKWISE,
    };

    return translation_table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_front_face_to_vk_front_face  vd_cgla_front_face_to_vk_front_face 
#endif // VD_MACRO_ABBREVIATIONS

/* ----VK COMPARE OP------------------------------------------------------------------------------------------------- */
static VD_INLINE VkCompareOp vd_cgla_compare_operator_to_vk_compare_op(VD_CGLA_COMPARE_OPERATOR_TYPE type)
{
    static VkCompareOp translation_table[VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_MAX)] = {
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_NEVER)]   = VK_COMPARE_OP_NEVER,
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_LESS)]    = VK_COMPARE_OP_LESS,
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_EQUAL)]   = VK_COMPARE_OP_EQUAL,
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_LEQUAL)]  = VK_COMPARE_OP_LESS_OR_EQUAL,
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_GREATER)] = VK_COMPARE_OP_GREATER,
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_GEQUAL)]  = VK_COMPARE_OP_GREATER_OR_EQUAL,
        [VD_CGLA_COMPARE_OPERATOR_NAME(COMPARE_OPERATOR_ALWAYS)]  = VK_COMPARE_OP_ALWAYS,
    };

    return translation_table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_compare_operator_to_vk_compare_op  vd_cgla_compare_operator_to_vk_compare_op 
#endif // VD_MACRO_ABBREVIATIONS

/* ----VK IMAGE LAYOUT----------------------------------------------------------------------------------------------- */
static VD_INLINE VkImageLayout vd_cgla_image_layout_to_vk_image_layout(VD_CGLA_IMAGE_LAYOUT_TYPE type)
{
    static VkImageLayout translation_table[VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_MAX)] = {
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_UNDEFINED)]                                  = VK_IMAGE_LAYOUT_UNDEFINED,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_GENERAL)]                                    = VK_IMAGE_LAYOUT_GENERAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL)]                   = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL)]           = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL)]            = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL)]                   = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL)]                       = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL)]                       = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_PREINITIALIZED)]                             = VK_IMAGE_LAYOUT_PREINITIALIZED,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL)] = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL)] = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL)]                   = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL)]                    = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL)]                 = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL)]                  = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_READ_ONLY_OPTIMAL)]                          = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_ATTACHMENT_OPTIMAL)]                         = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_RENDERING_LOCAL_READ)]                       = VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_PRESENT_SRC)]                                = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_VIDEO_DECODE_DST)]                           = VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_VIDEO_DECODE_SRC)]                           = VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR,
        [VD_CGLA_IMAGE_LAYOUT_NAME(IMAGE_LAYOUT_VIDEO_DECODE_DPB)]                           = VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR,
    };

    return translation_table[type];
}

#if VD_MACRO_ABBREVIATIONS
#define cgla_image_layout_to_vk_image_layout  vd_cgla_image_layout_to_vk_image_layout 
#endif // VD_MACRO_ABBREVIATIONS

#endif // VD_CGLA_VK_IMPL